# Generated by Django 3.2.15 on 2023-07-08 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20230703_2123'),
    ]

    operations = [
    ]
